kind: pipeline
type: docker
name: build-lint-and-test

steps:
- name: build
  commands:
  - make
  environment:
    GOOS: linux
    GOARCH: amd64

- name: lint
  commands:
  - apt update && apt install -y cppcheck
  - cppcheck --enable=all --inconclusive .
  environment:
    GOOS: linux
    GOARCH: amd64    

- name: test
  commands:
  - git submodule update --init --recursive
  - make test
  environment:
    GOOS: linux
    GOARCH: amd64    