DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_GITLEAKS
  - REPOSITORY_GIT_DIFF  
  - SPELL_MISSPELL
  - SPELL_LYCHEE
  - SPELL_CSPELL
  - C_CLANG_FORMAT
  - C_CPPLINT
  - CPP_CLANG_FORMAT
  - CPP_CPPLINT
  - YAML_YAMLLINT
  - YAML_V8R
  - YAML_PRETTIER
  - BASH_SHFMT
