# MoClo pipeline based on "Starter"
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: apt update && apt install -y build-essential
  displayName: 'Install dependencies'

- script: |
    make
  displayName: 'Build this'
