steps:
- name: 'ubuntu'
  script: |    
    apt update && apt install -y build-essential make
    make
- name: 'ubuntu'
  script: |
    apt update && apt install -y build-essential make git
    git submodule update --init --recursive
    make test