# SPDX-License-Identifier: MIT

name: 'Build'

on: [push]

jobs:
  lint:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: apt update && apt install -y build-essential
      - name: Build this
        run: make