# SPDX-License-Identifier: MIT

name: 'Lint'

on: [push]

jobs:
  lint:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Install cppcheck
        run: apt update && apt install -y cppcheck
      - name: Lint this
        run: cppcheck --enable=all --suppress=missingIncludeSystem .