# SPDX-License-Identifier: MIT

name: 'Test'

on: [push]

jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: apt update && apt install -y libssl-dev build-essential cppcheck
      - name: Test this
        run: make test