name: moclo lint
run-name: ${{ gitea.actor }} is linting moclo 🚀
on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out moclo code
        uses: actions/checkout@v4
      - name: Install cppcheck
        run: apt update && apt install -y cppcheck
      - name: Lint code
        run: cppcheck --enable=all --suppress=missingIncludeSystem .
