name: moclo lint
run-name: ${{ gitea.actor }} is linting moclo 🚀
on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out moclo code
        uses: actions/checkout@v4
      - name: Lint code
        uses: megalinter/megalinter/flavors/c_cpp@v8
        env:
          DEFAULT_BRANCH: dev
          VALIDATE_ALL_CODEBASE: false
