name: Lint

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y make gcc cppcheck
      - name: Lint this
        run: cppcheck --enable=all --suppress=missingIncludeSystem .
