name: Test

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Update submodules
        run: |
          git submodule update --init --recursive
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y make gcc
      - name: Test this
        run: make test
